# Generated by Django 3.0 on 2019-12-13 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jogada',
            old_name='linhas',
            new_name='linha',
        ),
    ]
